-- Supply Chain Optimizer Database Schema
-- MySQL 8.0+

-- Create database if it doesn't exist

    shipment_id VARCHAR(50) UNIQUE NOT NULL,
-- Supply Chain Optimizer Oracle Database Schema
-- Run this script while connected to the Oracle application user in SQL Developer.

CREATE TABLE shipments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id VARCHAR2(50) UNIQUE NOT NULL,
    origin VARCHAR2(100) NOT NULL,
    destination VARCHAR2(100) NOT NULL,
    cargo_description CLOB,
    cargo_value NUMBER(15, 2),
    is_cold_chain NUMBER(1) DEFAULT 0 NOT NULL,
    status VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    current_location VARCHAR2(100),
    planned_delivery TIMESTAMP,
    estimated_delivery TIMESTAMP,
    actual_delivery TIMESTAMP,
    carrier VARCHAR2(100),
    container_id VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_shipments_cold_chain CHECK (is_cold_chain IN (0, 1)),
    CONSTRAINT ck_shipments_status CHECK (status IN ('pending', 'in_transit', 'delayed', 'diverted', 'delivered', 'cancelled'))
);

CREATE TABLE disruptions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disruption_id VARCHAR2(50) UNIQUE NOT NULL,
    title VARCHAR2(200) NOT NULL,
    description CLOB,
    disruption_type VARCHAR2(50),
    affected_region VARCHAR2(100) NOT NULL,
    severity VARCHAR2(20) DEFAULT 'medium' NOT NULL,
    start_time TIMESTAMP NOT NULL,
    estimated_resolution TIMESTAMP,
    affected_shipments_count NUMBER DEFAULT 0,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_disruptions_active CHECK (is_active IN (0, 1)),
    CONSTRAINT ck_disruptions_severity CHECK (severity IN ('low', 'medium', 'high', 'critical'))
);

CREATE TABLE fleet_assets (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id VARCHAR2(50) UNIQUE NOT NULL,
    asset_type VARCHAR2(50) NOT NULL,
    status VARCHAR2(20) DEFAULT 'idle',
    current_location VARCHAR2(100),
    capacity_tons NUMBER(10, 2),
    is_cold_chain_capable NUMBER(1) DEFAULT 0 NOT NULL,
    current_shipment VARCHAR2(50),
    available_from TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_fleet_cold_chain CHECK (is_cold_chain_capable IN (0, 1))
);

CREATE TABLE cold_chain_sensors (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id VARCHAR2(50) NOT NULL,
    shipment_id VARCHAR2(50) NOT NULL,
    container_id VARCHAR2(50),
    latitude NUMBER(10, 8),
    longitude NUMBER(11, 8),
    temperature NUMBER(5, 2) NOT NULL,
    humidity NUMBER(5, 2),
    timestamp TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE temperature_alerts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id VARCHAR2(50) UNIQUE NOT NULL,
    shipment_id VARCHAR2(50) NOT NULL,
    sensor_id VARCHAR2(50),
    temperature_recorded NUMBER(5, 2),
    expected_min NUMBER(5, 2),
    expected_max NUMBER(5, 2),
    duration_minutes NUMBER,
    severity VARCHAR2(20) DEFAULT 'info' NOT NULL,
    regulatory_impact CLOB,
    timestamp TIMESTAMP NOT NULL,
    acknowledged NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_alerts_acknowledged CHECK (acknowledged IN (0, 1)),
    CONSTRAINT ck_alerts_severity CHECK (severity IN ('info', 'warning', 'critical'))
);

CREATE TABLE route_recommendations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id VARCHAR2(50) NOT NULL,
    disruption_id VARCHAR2(50),
    original_route CLOB,
    recommended_route CLOB,
    alternative_carrier VARCHAR2(100),
    cost_impact NUMBER(12, 2),
    time_impact_hours NUMBER,
    risk_score NUMBER(5, 2),
    implemented NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_routes_implemented CHECK (implemented IN (0, 1))
);

CREATE INDEX idx_shipments_status ON shipments(status);
CREATE INDEX idx_shipments_carrier ON shipments(carrier);
CREATE INDEX idx_shipments_container ON shipments(container_id);
CREATE INDEX idx_shipments_cold_chain ON shipments(is_cold_chain);
CREATE INDEX idx_disruptions_active ON disruptions(is_active);
CREATE INDEX idx_disruptions_region ON disruptions(affected_region);
CREATE INDEX idx_disruptions_severity ON disruptions(severity);
CREATE INDEX idx_fleet_status ON fleet_assets(status);
CREATE INDEX idx_fleet_type ON fleet_assets(asset_type);
CREATE INDEX idx_fleet_cold_chain ON fleet_assets(is_cold_chain_capable);
CREATE INDEX idx_sensor_shipment ON cold_chain_sensors(shipment_id);
CREATE INDEX idx_sensor_container ON cold_chain_sensors(container_id);
CREATE INDEX idx_sensor_timestamp ON cold_chain_sensors(timestamp);
CREATE INDEX idx_alert_shipment ON temperature_alerts(shipment_id);
CREATE INDEX idx_alert_severity ON temperature_alerts(severity);
CREATE INDEX idx_alert_acknowledged ON temperature_alerts(acknowledged);
CREATE INDEX idx_route_shipment ON route_recommendations(shipment_id);
CREATE INDEX idx_route_disruption ON route_recommendations(disruption_id);
CREATE INDEX idx_route_implemented ON route_recommendations(implemented);

COMMIT;
);

-- Create indexes for performance optimization
CREATE INDEX idx_shipments_status_location ON shipments(status, current_location);
CREATE INDEX idx_disruptions_active_region ON disruptions(is_active, affected_region);
CREATE INDEX idx_alerts_shipment_severity ON temperature_alerts(shipment_id, severity);
